# Generated by Django 5.1.3 on 2024-11-21 15:46

from django.db import migrations

def insert_initial_usuario(apps, schema_editor):
    Usuario = apps.get_model('api', 'Usuario')
    Usuario.objects.get_or_create(nome='Getúlio', email='getulio@olá.com')
    Usuario.objects.get_or_create(nome='Maria Oliveira', email='maria.oliveira@eai.com')
    Usuario.objects.get_or_create(nome='Amanda', email='amanda@blz.com')
    Usuario.objects.get_or_create(nome='Alguma coisa', email='coisa@c.com')

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_create_initial_usuario'),
    ]

    operations = [
        migrations.RunPython(insert_initial_usuario),
    ]
