# Generated by Django 5.1.3 on 2024-11-21 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_insert_initial_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('comprimento', models.EmailField(max_length=254)),
                ('criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
