# Generated by Django 5.1.3 on 2024-11-21 16:01

from django.db import migrations


def insert_initial_medida(apps, schema_editor):
    Medida = apps.get_model('api', 'Medida')
    Medida.objects.get_or_create(descricao='Tábua', comprimento='10m²')
    Medida.objects.get_or_create(descricao='Treliça', comprimento='20m')
    Medida.objects.get_or_create(descricao='Viga', comprimento='15m³')
    Medida.objects.get_or_create(descricao='Telha 9mm', comprimento='25m²')

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_create_initial_medida'),
    ]

    operations = [
        migrations.RunPython(insert_initial_medida),
    ]
