# Generated by Django 5.1.3 on 2024-11-21 16:19

from django.db import migrations

def alter_initial_usuario(apps, schema_editor):
    Usuario = apps.get_model('api', 'Usuario')
    Usuario.objects.get_or_create(nome='GG1', email='GG1@g.com')
    Usuario.objects.get_or_create(nome='GG2', email='GG2@g.com')
    Usuario.objects.get_or_create(nome='GG3', email='GG3@g.com')

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_insert_initial_medida'),
    ]

    operations = [
        migrations.RunPython(alter_initial_usuario),
    ]
