# Generated by Django 5.1.3 on 2024-11-22 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_create_initial_adimistrador'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='id_administrador',
            field=models.ForeignKey(
                null=True, 
                blank=True, 
                on_delete=models.CASCADE, 
                to='api.administrador',
                db_column='id_administrador'
                ),
        ),
    ]
